/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import ModeloConection.ConexãoSQL;

import ModeloDao.DaoProdutos;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

import modeloBeans.BeansProdutos;
import modeloBeans.ModeloTabela;

/**
 *
 * @author iurya
 */
public class CadastroProdutos extends javax.swing.JFrame {
BeansProdutos mod = new BeansProdutos();
    DaoProdutos control = new DaoProdutos();
    ConexãoSQL conex = new ConexãoSQL();
    int flag = 0;
    
    /**
     * Creates new form CadastroProdutos
     */
    public CadastroProdutos() {
        initComponents();
        
        try {
            MaskFormatter form = new MaskFormatter("#####");//elemento que cria o formato da data
            CampoCodigoProduto.setFormatterFactory(new DefaultFormatterFactory(form));
        } catch (ParseException ex) {
            Logger.getLogger(RegistroVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
        preencherTabela("select * from tbprodutos order by nome_produto");
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CampoDescriçãoProdutos = new javax.swing.JTextField();
        ButtonNovoProduto = new javax.swing.JButton();
        ButtonSalvarProduto = new javax.swing.JButton();
        ButtonCancelarProduto = new javax.swing.JButton();
        ButtonEditarProduto = new javax.swing.JButton();
        ButonExcluirProduto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CampoUnidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CampoPreço = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaProdutos = new javax.swing.JTable();
        CampoPesquisar = new javax.swing.JTextField();
        ButtonPesquisar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        CampoPrecoCompra = new javax.swing.JTextField();
        CampoCodigoProduto = new javax.swing.JFormattedTextField();
        campoId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Código Produto:");

        jLabel3.setText("Descrição:");

        CampoDescriçãoProdutos.setEnabled(false);

        ButtonNovoProduto.setBackground(new java.awt.Color(0, 255, 0));
        ButtonNovoProduto.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ButtonNovoProduto.setText("Novo");
        ButtonNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNovoProdutoActionPerformed(evt);
            }
        });

        ButtonSalvarProduto.setBackground(new java.awt.Color(0, 255, 0));
        ButtonSalvarProduto.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ButtonSalvarProduto.setText("Salvar");
        ButtonSalvarProduto.setEnabled(false);
        ButtonSalvarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarProdutoActionPerformed(evt);
            }
        });

        ButtonCancelarProduto.setBackground(new java.awt.Color(255, 0, 0));
        ButtonCancelarProduto.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ButtonCancelarProduto.setText("Cancelar");
        ButtonCancelarProduto.setEnabled(false);
        ButtonCancelarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarProdutoActionPerformed(evt);
            }
        });

        ButtonEditarProduto.setBackground(new java.awt.Color(0, 255, 0));
        ButtonEditarProduto.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ButtonEditarProduto.setText("Editar");
        ButtonEditarProduto.setEnabled(false);
        ButtonEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarProdutoActionPerformed(evt);
            }
        });

        ButonExcluirProduto.setBackground(new java.awt.Color(0, 255, 51));
        ButonExcluirProduto.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ButonExcluirProduto.setText("Excluir");
        ButonExcluirProduto.setEnabled(false);
        ButonExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButonExcluirProdutoActionPerformed(evt);
            }
        });

        jLabel4.setText("Unidades:");

        CampoUnidade.setEnabled(false);

        jLabel5.setText("Preço venda:");

        CampoPreço.setEnabled(false);
        CampoPreço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPreçoActionPerformed(evt);
            }
        });

        jLabel6.setText("R$:");

        TabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaProdutos);

        ButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Localizar.png"))); // NOI18N
        ButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPesquisarActionPerformed(evt);
            }
        });

        jLabel7.setText("Preço compra R$:");

        CampoPrecoCompra.setEnabled(false);
        CampoPrecoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPrecoCompraActionPerformed(evt);
            }
        });

        CampoCodigoProduto.setEnabled(false);
        CampoCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCodigoProdutoActionPerformed(evt);
            }
        });

        campoId.setEditable(false);
        campoId.setEnabled(false);

        jLabel8.setText("ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButonExcluirProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonEditarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonNovoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonSalvarProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonCancelarProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(1, 1, 1)
                                        .addComponent(CampoCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CampoDescriçãoProdutos))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(126, 126, 126))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel4)
                                .addGap(4, 4, 4)
                                .addComponent(CampoUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoPreço, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CampoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonPesquisar)
                                .addGap(157, 157, 157))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 113, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(4, 4, 4)
                .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonNovoProduto)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(CampoDescriçãoProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonSalvarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonEditarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButonExcluirProduto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(CampoPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(CampoUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoPreço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(CampoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonPesquisar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCancelarProduto))
                .addGap(219, 219, 219))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro Produtos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(835, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNovoProdutoActionPerformed
      CampoCodigoProduto.setText("");
      CampoDescriçãoProdutos.setText("");
      CampoUnidade.setText("");
      CampoPreço.setText("");
      CampoPesquisar.setText("");
      CampoPrecoCompra.setText("");
      
//ativa os butoes ao clicar em novo
        flag = 1;
        ButtonSalvarProduto.setEnabled(true);
        ButonExcluirProduto.setEnabled(true);
        ButtonCancelarProduto.setEnabled(true);
        ButtonEditarProduto.setEnabled(true);
        //ativa os campos ao clicar em novo
        CampoCodigoProduto.setEnabled(true);
        CampoDescriçãoProdutos.setEnabled(true);
        CampoUnidade.setEnabled(true);
        CampoPreço.setEnabled(true);
        CampoPrecoCompra.setEnabled(true);
    }//GEN-LAST:event_ButtonNovoProdutoActionPerformed

    private void ButtonSalvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarProdutoActionPerformed
       //f(campoNomeCliente.getText().isEmpty());{
       //OptionPane.showMessageDialog(null, "Preencha o NOme para continuar");
       //ampoNomeCliente.requestFocus();   
   //
                if(flag ==1){
      mod.setCodigo_produto(CampoCodigoProduto.getText());
      mod.setDescrição(CampoDescriçãoProdutos.getText());
      mod.setQuantidade(Integer.parseInt(CampoUnidade.getText()));
      mod.setPreco(Double.parseDouble(CampoPreço.getText()));
     mod.setPrecoCompra(Double.parseDouble(CampoPrecoCompra.getText()));
      
      control.Salvar(mod);
      //depois de salvar os campos fica em branco
      CampoCodigoProduto.setText("");
      CampoDescriçãoProdutos.setText("");
      CampoUnidade.setText("");
      CampoPreço.setText("");
      CampoPesquisar.setText("");
      CampoPrecoCompra.setText("");
      
      CampoCodigoProduto.setEnabled(false);
      CampoDescriçãoProdutos.setEnabled(false);
      CampoUnidade.setEnabled(false);
      CampoPreço.setEnabled(false);
      CampoPrecoCompra.setEnabled(false);
      
      ButtonSalvarProduto.setEnabled(false);
      ButtonEditarProduto.setEnabled(false);
      ButtonCancelarProduto.setEnabled(false);
      ButonExcluirProduto.setEnabled(false);
    }
    else{
    mod.setCodigo_produto(CampoCodigoProduto.getText());
    mod.setDescrição(CampoDescriçãoProdutos.getText());
   mod.setQuantidade(Integer.parseInt(CampoUnidade.getText()));
   mod.setPreco(Double.parseDouble(CampoPreço.getText()));
    mod.setPrecoCompra(Double.parseDouble(CampoPrecoCompra.getText()));
    
    control.Editar(mod);
    
     CampoCodigoProduto.setText(""); //edita e os campos fica em branco
      CampoDescriçãoProdutos.setText("");
      CampoUnidade.setText("");
      CampoPreço.setText("");
      CampoPrecoCompra.setText("");
      
    CampoCodigoProduto.setEnabled(false);
      CampoDescriçãoProdutos.setEnabled(false);
      CampoUnidade.setEnabled(false);
      CampoPreço.setEnabled(false);
      CampoPrecoCompra.setEnabled(false);
      
      ButtonNovoProduto.setEnabled(false);
      ButtonEditarProduto.setEnabled(false);
      ButtonCancelarProduto.setEnabled(false);
      ButonExcluirProduto.setEnabled(false);
      ButtonNovoProduto.setEnabled(true);
      CampoPesquisar.setText("");
    
        }                                         
    }//GEN-LAST:event_ButtonSalvarProdutoActionPerformed

    private void ButtonEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarProdutoActionPerformed
         //ativa os butoes ao clicar em editar
        flag = 2;
        ButtonNovoProduto.setEnabled(false);
        ButtonSalvarProduto.setEnabled(true);
        ButonExcluirProduto.setEnabled(false);
        ButtonCancelarProduto.setEnabled(true);
        ButtonEditarProduto.setEnabled(false);
        //ativa os campos ao clicar em editar
        CampoCodigoProduto.setEnabled(true);
        CampoDescriçãoProdutos.setEnabled(true);
        CampoPreço.setEnabled(true);
        CampoUnidade.setEnabled(true);
        CampoPrecoCompra.setEnabled(true);
    }//GEN-LAST:event_ButtonEditarProdutoActionPerformed

    private void ButtonCancelarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarProdutoActionPerformed
      ButtonSalvarProduto.setEnabled(!true);
        ButonExcluirProduto.setEnabled(false);
        ButtonCancelarProduto.setEnabled(!true);
        ButtonNovoProduto.setEnabled(true);
       ButtonEditarProduto.setEnabled(false);
        
        CampoCodigoProduto.setEnabled(!true);
        CampoDescriçãoProdutos.setEnabled(!true);
        CampoPreço.setEnabled(!true);
        CampoUnidade.setEnabled(!true);
        CampoPrecoCompra.setEnabled(!true);
        
        // ao cancelar limpa os campos
        CampoCodigoProduto.setText(""); 
      CampoDescriçãoProdutos.setText("");
      CampoPreço.setText("");
      CampoUnidade.setText("");
      CampoPesquisar.setText("");
      CampoPrecoCompra.setText("");
    }//GEN-LAST:event_ButtonCancelarProdutoActionPerformed

    private void ButonExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonExcluirProdutoActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente Excluir?");
        if(resposta == JOptionPane.YES_OPTION ){
            
        mod.setCodigo_produto(CampoCodigoProduto.getText());
        control.Excluir(mod);
        
        //depois de excluir os campos fica em branco
      CampoCodigoProduto.setText("");
      CampoDescriçãoProdutos.setText("");
      CampoUnidade.setText("");
      CampoPreço.setText("");
      CampoPrecoCompra.setText("");
      
      ButtonSalvarProduto.setEnabled(false);
      ButtonEditarProduto.setEnabled(false);
      ButtonCancelarProduto.setEnabled(true);
      ButonExcluirProduto.setEnabled(false);
      ButtonNovoProduto.setEnabled(true);
      CampoPesquisar.setText("");
        }
                             
    }//GEN-LAST:event_ButonExcluirProdutoActionPerformed

    private void ButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPesquisarActionPerformed
         mod.setPesquisa(CampoPesquisar.getText());
        BeansProdutos model = control.buscaProduto(mod);
        
        CampoCodigoProduto.setText(model.getCodigo_produto());
        CampoDescriçãoProdutos.setText(model.getDescrição());
        CampoUnidade.setText(String.valueOf(model.getQuantidade()));
        CampoPreço.setText(String.valueOf(model.getPreco()));
        CampoPrecoCompra.setText(String.valueOf(model.getPrecoCompra()));
        
        ButtonEditarProduto.setEnabled(true);
        ButonExcluirProduto.setEnabled(true);
    }//GEN-LAST:event_ButtonPesquisarActionPerformed

    private void CampoPreçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPreçoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPreçoActionPerformed

    private void CampoPrecoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPrecoCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPrecoCompraActionPerformed

    private void CampoCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCodigoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCodigoProdutoActionPerformed

    private void TabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaProdutosMouseClicked
      
       conex.conexão();
       
    try {
         String nome_produto =""+TabelaProdutos.getValueAt(TabelaProdutos.getSelectedRow(), 2);
                conex.execultaSql("select * from tbprodutos where nome_produto='"+nome_produto+"'");
         
        conex.rs.first();
         campoId.setText(String.valueOf(conex.rs.getInt("id_produto")));
        CampoDescriçãoProdutos.setText(conex.rs.getString("nome_produto"));
        CampoCodigoProduto.setText(conex.rs.getString("codigo_produto"));
        CampoPreço.setText(String.valueOf(conex.rs.getFloat("preco_venda")));
        CampoUnidade.setText(String.valueOf(conex.rs.getInt("quantidade")));
        CampoPrecoCompra.setText(String.valueOf(conex.rs.getFloat("preco_compra")));
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Erro ao selecionar dados"+ex);
   }
    
     
       conex.desconecta();
       ButonExcluirProduto.setEnabled(true);
       ButtonEditarProduto.setEnabled(true);
       
    }//GEN-LAST:event_TabelaProdutosMouseClicked
public void preencherTabela(String Sql){
    ArrayList dados = new ArrayList();
    String[] colunas = new String[]{" ID "," Código Produto "," Descrição "," Unidade "," R$ "};
    
    conex.conexão();
    conex.execultaSql(Sql);
    
    try{
        conex.rs.first();
        do{
           dados.add(new Object[]{conex.rs.getString("id_produto"),conex.rs.getString("codigo_produto"), conex.rs.getString("nome_produto"),conex.rs.getString("quantidade"),conex.rs.getString("preco_venda")});
            
        }while(conex.rs.next());
    }catch(SQLException ex){
        JOptionPane.showMessageDialog(rootPane, "Erro ao preencher um ArrayList"+ex);
    }
    ModeloTabela modelo = new ModeloTabela(dados, colunas);
    
    TabelaProdutos.setModel(modelo);
    TabelaProdutos.getColumnModel().getColumn(0).setPreferredWidth(50);
    TabelaProdutos.getColumnModel().getColumn(0).setResizable(false);
    
    TabelaProdutos.getColumnModel().getColumn(1).setPreferredWidth(120);//largura
    TabelaProdutos.getColumnModel().getColumn(1).setResizable(false);

    TabelaProdutos.getColumnModel().getColumn(2).setPreferredWidth(220);
    TabelaProdutos.getColumnModel().getColumn(2).setResizable(false);

    TabelaProdutos.getColumnModel().getColumn(3).setPreferredWidth(70);
    TabelaProdutos.getColumnModel().getColumn(3).setResizable(false);

    TabelaProdutos.getColumnModel().getColumn(4).setPreferredWidth(90);
    TabelaProdutos.getColumnModel().getColumn(4).setResizable(false);

    TabelaProdutos.getTableHeader().setResizingAllowed(false);
    TabelaProdutos.setAutoResizeMode(TabelaProdutos.AUTO_RESIZE_OFF);
    TabelaProdutos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     
     
        
    
    conex.desconecta();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButonExcluirProduto;
    private javax.swing.JButton ButtonCancelarProduto;
    private javax.swing.JButton ButtonEditarProduto;
    private javax.swing.JButton ButtonNovoProduto;
    private javax.swing.JButton ButtonPesquisar;
    private javax.swing.JButton ButtonSalvarProduto;
    private javax.swing.JFormattedTextField CampoCodigoProduto;
    private javax.swing.JTextField CampoDescriçãoProdutos;
    private javax.swing.JTextField CampoPesquisar;
    private javax.swing.JTextField CampoPrecoCompra;
    private javax.swing.JTextField CampoPreço;
    private javax.swing.JTextField CampoUnidade;
    private javax.swing.JTable TabelaProdutos;
    private javax.swing.JTextField campoId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
