/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import ModeloConection.ConexãoSQL;
import ModeloDao.DaoCliente;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import modeloBeans.BeansCliente;
import modeloBeans.ModeloTabela;

/**
 *
 * @author iurya
 */
public class FormularioClientes extends javax.swing.JFrame {
    
   

    BeansCliente mod = new BeansCliente();
    DaoCliente control = new DaoCliente();
    ConexãoSQL conex = new ConexãoSQL();
    int flag = 0;
    
    public FormularioClientes() {
        initComponents();
        try {
            MaskFormatter form = new MaskFormatter("##");//elemento que cria o formato da data
            CampoDDD.setFormatterFactory(new DefaultFormatterFactory(form));
        } catch (ParseException ex) {
            Logger.getLogger(RegistroVendas.class.getName()).log(Level.SEVERE, null, ex);
        }   
        try {
            MaskFormatter form = new MaskFormatter("###.###.###-##");//elemento que cria o formato da data
            CampoCpf.setFormatterFactory(new DefaultFormatterFactory(form));
        } catch (ParseException ex) {
            Logger.getLogger(RegistroVendas.class.getName()).log(Level.SEVERE, null, ex);
        }   
        try {
            MaskFormatter form = new MaskFormatter("#####-####");//elemento que cria o formato da data
            CampoTelefoneCelular.setFormatterFactory(new DefaultFormatterFactory(form));
        } catch (ParseException ex) {
            Logger.getLogger(RegistroVendas.class.getName()).log(Level.SEVERE, null, ex);
        }   
        try {
            MaskFormatter form = new MaskFormatter("####-####");//elemento que cria o formato da data
            CampoTelefoneResidencial.setFormatterFactory(new DefaultFormatterFactory(form));
        } catch (ParseException ex) {
            Logger.getLogger(RegistroVendas.class.getName()).log(Level.SEVERE, null, ex);
        }   
        try {
            MaskFormatter form = new MaskFormatter("####-####");//elemento que cria o formato da data
            CampoTelefoneComercial.setFormatterFactory(new DefaultFormatterFactory(form));
        } catch (ParseException ex) {
            Logger.getLogger(RegistroVendas.class.getName()).log(Level.SEVERE, null, ex);
            
        }   
         try {
            MaskFormatter form = new MaskFormatter("#####-###");//elemento que cria o formato da data
            CampoCEP.setFormatterFactory(new DefaultFormatterFactory(form));
        } catch (ParseException ex) {
            Logger.getLogger(RegistroVendas.class.getName()).log(Level.SEVERE, null, ex);
        }   
        
        preencherTabela("select * from tbcliente order by nome");
        this.setLocationRelativeTo(null);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomeC = new javax.swing.JLabel();
        jLabel3Cpf = new javax.swing.JLabel();
        EndereçoC = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoNomeCliente = new javax.swing.JTextField();
        campoEndereço = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Uf = new javax.swing.JLabel();
        CampoUf = new javax.swing.JTextField();
        cidadeC = new javax.swing.JLabel();
        CampoCidade = new javax.swing.JTextField();
        ButtonNovo = new javax.swing.JButton();
        ButtonSalvar = new javax.swing.JButton();
        jLabel6Cep = new javax.swing.JLabel();
        CampoBairro = new javax.swing.JTextField();
        ButtonCancelar = new javax.swing.JButton();
        ButtonEditar = new javax.swing.JButton();
        ButtonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaCliente = new javax.swing.JTable();
        CampoPesquisar = new javax.swing.JTextField();
        ButtonPesquisar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CampoComplemento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CampoTelefoneResidencial = new javax.swing.JFormattedTextField();
        CampoTelefoneComercial = new javax.swing.JFormattedTextField();
        CampoTelefoneCelular = new javax.swing.JFormattedTextField();
        CampoDDD = new javax.swing.JFormattedTextField();
        CampoID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        CampoCpf = new javax.swing.JFormattedTextField();
        CampoCEP = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dialog", 0, 16), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setEnabled(false);

        nomeC.setText("Nome:");

        jLabel3Cpf.setText("CPF:");

        EndereçoC.setText("Endereço:");

        campoNomeCliente.setEnabled(false);
        campoNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeClienteActionPerformed(evt);
            }
        });

        campoEndereço.setEnabled(false);

        Uf.setText("Uf:");

        CampoUf.setEnabled(false);

        cidadeC.setText("Cidade:");

        CampoCidade.setEnabled(false);
        CampoCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCidadeActionPerformed(evt);
            }
        });

        ButtonNovo.setBackground(new java.awt.Color(0, 255, 0));
        ButtonNovo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ButtonNovo.setText("Novo");
        ButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNovoActionPerformed(evt);
            }
        });

        ButtonSalvar.setBackground(new java.awt.Color(0, 255, 0));
        ButtonSalvar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ButtonSalvar.setText("Salvar");
        ButtonSalvar.setEnabled(false);
        ButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarActionPerformed(evt);
            }
        });

        jLabel6Cep.setText("Bairro:");

        CampoBairro.setEnabled(false);

        ButtonCancelar.setBackground(new java.awt.Color(255, 0, 0));
        ButtonCancelar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ButtonCancelar.setText("Cancelar");
        ButtonCancelar.setEnabled(false);
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });

        ButtonEditar.setBackground(new java.awt.Color(0, 255, 0));
        ButtonEditar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ButtonEditar.setText("Editar");
        ButtonEditar.setEnabled(false);
        ButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarActionPerformed(evt);
            }
        });

        ButtonExcluir.setBackground(new java.awt.Color(0, 255, 0));
        ButtonExcluir.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ButtonExcluir.setText("Excluir");
        ButtonExcluir.setEnabled(false);
        ButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExcluirActionPerformed(evt);
            }
        });

        TabelaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TabelaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaCliente);

        CampoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPesquisarActionPerformed(evt);
            }
        });

        ButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Localizar.png"))); // NOI18N
        ButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPesquisarActionPerformed(evt);
            }
        });

        jLabel2.setText("Complemento:");

        CampoComplemento.setEnabled(false);

        jLabel3.setText("CEP:");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setEnabled(false);

        jLabel4.setText("Telefone:");

        jLabel5.setText("Celular:");

        jLabel6.setText("Residencial:");

        jLabel10.setText("Comercial:");

        jLabel11.setText("DDD:");

        CampoTelefoneResidencial.setEnabled(false);
        CampoTelefoneResidencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTelefoneResidencialActionPerformed(evt);
            }
        });

        CampoTelefoneComercial.setEnabled(false);
        CampoTelefoneComercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTelefoneComercialActionPerformed(evt);
            }
        });

        CampoTelefoneCelular.setEnabled(false);
        CampoTelefoneCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTelefoneCelularActionPerformed(evt);
            }
        });

        CampoDDD.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CampoDDD, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoTelefoneCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoTelefoneResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoTelefoneComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(CampoTelefoneResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoTelefoneCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoDDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CampoTelefoneComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        CampoID.setEnabled(false);
        CampoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoIDActionPerformed(evt);
            }
        });

        jLabel12.setText("ID:");

        CampoCpf.setEnabled(false);
        CampoCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCpfActionPerformed(evt);
            }
        });

        CampoCEP.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CampoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cidadeC)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CampoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Uf)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CampoUf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(391, 391, 391)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(EndereçoC)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoEndereço, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel6Cep))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CampoCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)))
                        .addContainerGap(72, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(341, 341, 341))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nomeC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel3Cpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(150, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoID, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CampoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CampoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)
                                .addComponent(CampoID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nomeC)
                                .addComponent(campoNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3Cpf)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6Cep)
                                .addComponent(CampoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoEndereço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EndereçoC))
                            .addComponent(jLabel9))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cidadeC)
                            .addComponent(CampoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Uf)
                            .addComponent(CampoUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(CampoComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(CampoCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(ButtonNovo)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonEditar))
                    .addComponent(ButtonExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CampoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(997, 733));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CampoCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCidadeActionPerformed

    private void ButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarActionPerformed
   
       //f(campoNomeCliente.getText().isEmpty());{
       //OptionPane.showMessageDialog(null, "Preencha o NOme para continuar");
       //ampoNomeCliente.requestFocus();   
   //
                if(flag ==1){
      mod.setNome(campoNomeCliente.getText());
      mod.setCpf(CampoCpf.getText());
      mod.setEndereco(campoEndereço.getText());
      mod.setBairro(CampoBairro.getText());
      mod.setCidade(CampoCidade.getText());
      mod.setUf(CampoUf.getText());
      mod.setComplemento(CampoComplemento.getText());
      mod.setCep(CampoCEP.getText());
      mod.setDDD(CampoDDD.getText());
      mod.setTelefoneCelular(CampoTelefoneCelular.getText());
      mod.setTelefoneComercial(CampoTelefoneComercial.getText());
      mod.setTelefoneResidencial(CampoTelefoneResidencial.getText());
      
      control.Salvar(mod);
      //depois de salvar os campos fica em branco
      campoNomeCliente.setText("");
      CampoCpf.setText("");
      campoEndereço.setText("");
      CampoBairro.setText("");
      CampoCidade.setText("");
      CampoUf.setText("");
      CampoComplemento.setText("");
      CampoCEP.setText("");
      CampoDDD.setText("");
      CampoTelefoneCelular.setText("");
      CampoTelefoneComercial.setText("");
      CampoTelefoneResidencial.setText("");
      CampoPesquisar.setText("");
      
      campoNomeCliente.setEnabled(false);
      CampoCpf.setEnabled(false);
      campoEndereço.setEnabled(false);
      CampoComplemento.setEnabled(false);
      CampoCidade.setEnabled(false);
      CampoBairro.setEnabled(false);
      CampoUf.setEnabled(false);
      CampoCEP.setEnabled(false);
      CampoDDD.setEnabled(false);
      CampoTelefoneCelular.setEnabled(false);
      CampoTelefoneComercial.setEnabled(false);
      CampoTelefoneResidencial.setEnabled(false);
      
      ButtonSalvar.setEnabled(false);
      ButtonEditar.setEnabled(false);
      ButtonCancelar.setEnabled(false);
      ButtonExcluir.setEnabled(false);
    }
    else{
    mod.setCpf(CampoCpf.getText());
    mod.setNome(campoNomeCliente.getText());
    mod.setEndereco(campoEndereço.getText());
    mod.setComplemento(CampoComplemento.getText());
    mod.setCep(CampoCEP.getText());
    mod.setUf(CampoUf.getText());
    mod.setCidade(CampoCidade.getText());
    mod.setBairro(CampoBairro.getText());
    mod.setDDD(CampoDDD.getText());
    mod.setTelefoneCelular(CampoTelefoneCelular.getText());
    mod.setTelefoneComercial(CampoTelefoneComercial.getText());
    mod.setTelefoneResidencial(CampoTelefoneResidencial.getText());
    
    control.Editar(mod);
    
     campoNomeCliente.setText(""); //edita e os campos fica em branco
      CampoCpf.setText("");
      campoEndereço.setText("");
      CampoBairro.setText("");
      CampoCidade.setText("");
      CampoUf.setText("");
      CampoComplemento.setText("");
      CampoCEP.setText("");
      CampoDDD.setText("");
      CampoTelefoneCelular.setText("");
      CampoTelefoneComercial.setText("");
      CampoTelefoneResidencial.setText("");
    
    campoNomeCliente.setEnabled(false);
      CampoCpf.setEnabled(false);
      campoEndereço.setEnabled(false);
      CampoComplemento.setEnabled(false);
      CampoCidade.setEnabled(false);
      CampoBairro.setEnabled(false);
      CampoUf.setEnabled(false);
      CampoCEP.setEnabled(false);
      CampoDDD.setEnabled(false);
      CampoTelefoneCelular.setEnabled(false);
      CampoTelefoneComercial.setEnabled(false);
      CampoTelefoneResidencial.setEnabled(false);
      
      ButtonSalvar.setEnabled(false);
      ButtonEditar.setEnabled(false);
      ButtonCancelar.setEnabled(false);
      ButtonExcluir.setEnabled(false);
      ButtonNovo.setEnabled(true);
      CampoPesquisar.setText("");
    }
      
      
      
      
    }//GEN-LAST:event_ButtonSalvarActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        ButtonSalvar.setEnabled(!true);
        ButtonExcluir.setEnabled(false);
        ButtonCancelar.setEnabled(!true);
        ButtonNovo.setEnabled(true);
        ButtonEditar.setEnabled(false);
        
        campoNomeCliente.setEnabled(!true);
        campoEndereço.setEnabled(!true);
        CampoCEP.setEnabled(!true);
        CampoCidade.setEnabled(!true);
        CampoBairro.setEnabled(!true);
        CampoDDD.setEnabled(!true);
        CampoTelefoneCelular.setEnabled(!true);
        CampoTelefoneComercial.setEnabled(!true);
        CampoTelefoneResidencial.setEnabled(!true);
        CampoComplemento.setEnabled(!true);
        CampoCpf.setEnabled(!true);
        CampoUf.setEnabled(!true);
        
        // ao cancelar limpa os campos
        campoNomeCliente.setText(""); 
      CampoCpf.setText("");
      campoEndereço.setText("");
      CampoBairro.setText("");
      CampoCidade.setText("");
      CampoUf.setText("");
      CampoComplemento.setText("");
      CampoCEP.setText("");
      CampoDDD.setText("");
      CampoTelefoneCelular.setText("");
      CampoTelefoneComercial.setText("");
      CampoTelefoneResidencial.setText("");
      CampoPesquisar.setText("");
    }//GEN-LAST:event_ButtonCancelarActionPerformed

    private void ButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarActionPerformed
        //ativa os butoes ao clicar em editar
        flag = 2;
        ButtonNovo.setEnabled(false);
        ButtonSalvar.setEnabled(true);
        ButtonExcluir.setEnabled(false);
        ButtonCancelar.setEnabled(true);
        ButtonEditar.setEnabled(false);
        //ativa os campos ao clicar em editar
        campoNomeCliente.setEnabled(true);
        campoEndereço.setEnabled(true);
        CampoCEP.setEnabled(true);
        CampoCidade.setEnabled(true);
        CampoBairro.setEnabled(true);
        CampoDDD.setEnabled(true);
        CampoTelefoneCelular.setEnabled(true);
        CampoTelefoneComercial.setEnabled(true);
        CampoTelefoneResidencial.setEnabled(true);
        CampoComplemento.setEnabled(true);
        CampoCpf.setEnabled(true);
        CampoUf.setEnabled(true);
    }//GEN-LAST:event_ButtonEditarActionPerformed

    private void CampoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPesquisarActionPerformed

    private void ButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNovoActionPerformed
        CampoPesquisar.setText("");
        campoNomeCliente.setText("");
      CampoCpf.setText("");
      campoEndereço.setText("");
      CampoBairro.setText("");
      CampoCidade.setText("");
      CampoUf.setText("");
      CampoComplemento.setText("");
      CampoCEP.setText("");
      CampoDDD.setText("");
      CampoTelefoneCelular.setText("");
      CampoTelefoneComercial.setText("");
      CampoTelefoneResidencial.setText("");
//ativa os butoes ao clicar em novo
        flag = 1;
        ButtonSalvar.setEnabled(true);
        ButtonExcluir.setEnabled(true);
        ButtonCancelar.setEnabled(true);
        ButtonEditar.setEnabled(true);
        //ativa os campos ao clicar em novo
        campoNomeCliente.setEnabled(true);
        campoEndereço.setEnabled(true);
        CampoCEP.setEnabled(true);
        CampoCidade.setEnabled(true);
        CampoBairro.setEnabled(true);
        CampoDDD.setEnabled(true);
        CampoTelefoneCelular.setEnabled(true);
        CampoTelefoneComercial.setEnabled(true);
        CampoTelefoneResidencial.setEnabled(true);
        CampoComplemento.setEnabled(true);
        CampoCpf.setEnabled(true);
        CampoUf.setEnabled(true);
    }//GEN-LAST:event_ButtonNovoActionPerformed

    private void ButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPesquisarActionPerformed
        mod.setPesquisa(CampoPesquisar.getText());
        BeansCliente model = control.buscaCliente(mod);
        
        campoNomeCliente.setText(model.getNome());
        CampoCpf.setText(model.getCpf());
        CampoCEP.setText(model.getCep());
        CampoBairro.setText(model.getBairro());
        CampoCidade.setText(model.getCidade());
        CampoComplemento.setText(model.getComplemento());
        CampoDDD.setText(model.getDDD());
        campoEndereço.setText(model.getEndereco());
        CampoTelefoneCelular.setText(model.getTelefoneCelular());
        CampoTelefoneComercial.setText(model.getTelefoneComercial());
        CampoTelefoneResidencial.setText(model.getTelefoneResidencial());
        CampoUf.setText(model.getUf());
        CampoID.setText(Integer.toString(model.getCodigo()));
        
      
        
        
        
        ButtonEditar.setEnabled(true);
        ButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_ButtonPesquisarActionPerformed

    private void CampoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoIDActionPerformed

    private void ButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente Excluir?");
        if(resposta == JOptionPane.YES_OPTION ){
            
        mod.setCpf(CampoCpf.getText());
        control.Excluir(mod);
        
        //depois de excluir os campos fica em branco
      campoNomeCliente.setText("");
      CampoCpf.setText("");
      campoEndereço.setText("");
      CampoBairro.setText("");
      CampoCidade.setText("");
      CampoUf.setText("");
      CampoComplemento.setText("");
      CampoCEP.setText("");
      CampoDDD.setText("");
      CampoTelefoneCelular.setText("");
      CampoTelefoneComercial.setText("");
      CampoTelefoneResidencial.setText("");
      CampoPesquisar.setText("");
      
      ButtonSalvar.setEnabled(false);
      ButtonEditar.setEnabled(false);
      ButtonCancelar.setEnabled(true);
      ButtonExcluir.setEnabled(false);
      ButtonNovo.setEnabled(true);
      CampoPesquisar.setText("");
        }
    }//GEN-LAST:event_ButtonExcluirActionPerformed

    private void TabelaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaClienteMouseClicked
        String  Nome_cliente =""+TabelaCliente.getValueAt(TabelaCliente.getSelectedRow(), 1);
        
        conex.conexão();
        conex.execultaSql("select * from tbcliente where nome='"+Nome_cliente+"'");
        try {
            conex.rs.first();
            CampoID.setText(String.valueOf(conex.rs.getInt("id_cliente")));
       campoNomeCliente.setText(conex.rs.getString("nome"));
        CampoCpf.setText(conex.rs.getString("cpf"));
        campoEndereço.setText(conex.rs.getString("endereco"));
        CampoBairro.setText(conex.rs.getString("bairro"));
        CampoCidade.setText(conex.rs.getString("cidade"));
        CampoUf.setText(conex.rs.getString("uf"));
        CampoComplemento.setText(conex.rs.getString("complemento"));
        CampoCEP.setText(conex.rs.getString("cep"));
        CampoDDD.setText(conex.rs.getString("ddd"));
        CampoTelefoneCelular.setText(conex.rs.getString("telefonecelular"));
        CampoTelefoneResidencial.setText(conex.rs.getString("telefoneresidencial"));
        CampoTelefoneComercial.setText(conex.rs.getString("telefonecomercial"));
       
            
       } catch (SQLException ex) {
           
            JOptionPane.showMessageDialog(rootPane,"Erro ao selecionar os dados!\nERRO:"+ex);
        }
        ButtonEditar.setEnabled(true);
    }//GEN-LAST:event_TabelaClienteMouseClicked

    private void CampoTelefoneResidencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTelefoneResidencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTelefoneResidencialActionPerformed

    private void CampoTelefoneComercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTelefoneComercialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTelefoneComercialActionPerformed

    private void CampoTelefoneCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTelefoneCelularActionPerformed
       
    }//GEN-LAST:event_CampoTelefoneCelularActionPerformed

    private void campoNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeClienteActionPerformed

    private void CampoCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCpfActionPerformed
    public void preencherTabela(String Sql){
    ArrayList dados = new ArrayList();
    String[] colunas = new String[]{"ID","Nome","CPF","DDD","Celular"};
    
    conex.conexão();
    conex.execultaSql(Sql);
    
    try{
        conex.rs.first();
        do{
           dados.add(new Object[]{conex.rs.getString("id_cliente"),conex.rs.getString("Nome"), conex.rs.getString("Cpf"),conex.rs.getString("DDD"),conex.rs.getString("TelefoneCelular")});
            
        }while(conex.rs.next());
    }catch(SQLException ex){
        JOptionPane.showMessageDialog(rootPane, "Erro ao preencher um ArrayList"+ex);
    }
    ModeloTabela modelo = new ModeloTabela(dados, colunas);
    
    TabelaCliente.setModel(modelo);
    TabelaCliente.getColumnModel().getColumn(0).setPreferredWidth(45);
    TabelaCliente.getColumnModel().getColumn(0).setResizable(false);
    
    TabelaCliente.getColumnModel().getColumn(1).setPreferredWidth(220);//largura
    TabelaCliente.getColumnModel().getColumn(1).setResizable(false);

    TabelaCliente.getColumnModel().getColumn(2).setPreferredWidth(120);
    TabelaCliente.getColumnModel().getColumn(2).setResizable(false);

    TabelaCliente.getColumnModel().getColumn(3).setPreferredWidth(45);
    TabelaCliente.getColumnModel().getColumn(3).setResizable(false);

    TabelaCliente.getColumnModel().getColumn(4).setPreferredWidth(120);
    TabelaCliente.getColumnModel().getColumn(4).setResizable(false);

    TabelaCliente.getTableHeader().setResizingAllowed(false);
    TabelaCliente.setAutoResizeMode(TabelaCliente.AUTO_RESIZE_OFF);
    TabelaCliente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     
     
        
    
    conex.desconecta();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormularioClientes().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonEditar;
    private javax.swing.JButton ButtonExcluir;
    private javax.swing.JButton ButtonNovo;
    private javax.swing.JButton ButtonPesquisar;
    private javax.swing.JButton ButtonSalvar;
    private javax.swing.JTextField CampoBairro;
    private javax.swing.JFormattedTextField CampoCEP;
    private javax.swing.JTextField CampoCidade;
    private javax.swing.JTextField CampoComplemento;
    private javax.swing.JFormattedTextField CampoCpf;
    private javax.swing.JFormattedTextField CampoDDD;
    private javax.swing.JTextField CampoID;
    private javax.swing.JTextField CampoPesquisar;
    private javax.swing.JFormattedTextField CampoTelefoneCelular;
    private javax.swing.JFormattedTextField CampoTelefoneComercial;
    private javax.swing.JFormattedTextField CampoTelefoneResidencial;
    private javax.swing.JTextField CampoUf;
    private javax.swing.JLabel EndereçoC;
    private javax.swing.JTable TabelaCliente;
    private javax.swing.JLabel Uf;
    private javax.swing.JTextField campoEndereço;
    private javax.swing.JTextField campoNomeCliente;
    private javax.swing.JLabel cidadeC;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3Cpf;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel6Cep;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomeC;
    // End of variables declaration//GEN-END:variables

    
}
