/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import ModeloConection.ConexãoSQL;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import modeloBeans.ModeloTabela;

/**
 *
 * @author iurya
 */
public class PesquisaVendas extends javax.swing.JFrame {
    
    
    ConexãoSQL conex = new ConexãoSQL();
    
    /**
     * Creates new form RelatorioVendas
     */
    public PesquisaVendas() {
        initComponents();
        
     try {
            MaskFormatter form = new MaskFormatter("##/##/####");//elemento que cria o formato da data
            campoData.setFormatterFactory(new DefaultFormatterFactory(form));
        } catch (ParseException ex) {
            Logger.getLogger(RegistroVendas.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonPesquisa = new javax.swing.JButton();
        campoData = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVendaRealizada = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaDetalhes = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa Venda");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisa de vendas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        buttonPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Localizar.png"))); // NOI18N
        buttonPesquisa.setText("Pesquisar");
        buttonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesquisaActionPerformed(evt);
            }
        });

        campoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataActionPerformed(evt);
            }
        });

        jLabel1.setText("Digite uma data:");

        tabelaVendaRealizada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaVendaRealizada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVendaRealizadaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaVendaRealizada);

        jLabel2.setText("Vendas Realizadas:");

        tabelaDetalhes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaDetalhes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaDetalhesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaDetalhes);

        jLabel3.setText("Detalhes da venda:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonPesquisa))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(buttonPesquisa))
                .addGap(61, 61, 61)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(648, 618));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataActionPerformed

    private void buttonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesquisaActionPerformed
        preencherTabela("select * from tbvenda inner join tbcliente on tbvenda.id_cliente = tbcliente.id_cliente where data_venda= '"+campoData.getText()+"'");
    }//GEN-LAST:event_buttonPesquisaActionPerformed

    private void tabelaVendaRealizadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaVendaRealizadaMouseClicked
        int cod;
        cod = (int)tabelaVendaRealizada.getValueAt(tabelaVendaRealizada.getSelectedRow(), 0);
        preencherTabelaDetalhes("select * from tbvenda inner join itens_venda_produto on tbvenda.id_venda = itens_venda_produto.id_venda inner join tbprodutos on itens_venda_produto.id_produto = tbprodutos.id_produto where tbvenda.id_venda ="+cod);
    }//GEN-LAST:event_tabelaVendaRealizadaMouseClicked

    private void tabelaDetalhesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDetalhesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaDetalhesMouseClicked

    public void preencherTabela(String Sql){
    ArrayList dados = new ArrayList();
    
    String[] colunas = new String[]{"ID","Data Venda","Valor da Venda","Cliente","Forma de Pagamento"};
    conex.conexão();
    conex.execultaSql(Sql);
    try{
        conex.rs.first();
        do{
           dados.add(new Object[]{conex.rs.getInt("id_venda"), conex.rs.getString("data_venda"), conex.rs.getString("valor_venda"), conex.rs.getString("nome"), conex.rs.getString("forma_pagamento")});
            
        }while(conex.rs.next());
    }catch(SQLException ex){
        JOptionPane.showMessageDialog(rootPane, "Erro ao preencher um ArrayList!\nErro:"+ex);
    }
    ModeloTabela modelo = new ModeloTabela(dados, colunas);
    
    tabelaVendaRealizada.setModel(modelo);
    tabelaVendaRealizada.getColumnModel().getColumn(0).setPreferredWidth(50);//largura
    tabelaVendaRealizada.getColumnModel().getColumn(0).setResizable(false);

    tabelaVendaRealizada.getColumnModel().getColumn(1).setPreferredWidth(100);
    tabelaVendaRealizada.getColumnModel().getColumn(1).setResizable(false);

    tabelaVendaRealizada.getColumnModel().getColumn(2).setPreferredWidth(100);//largura
    tabelaVendaRealizada.getColumnModel().getColumn(2).setResizable(false);
    
    tabelaVendaRealizada.getColumnModel().getColumn(3).setPreferredWidth(150);//largura
    tabelaVendaRealizada.getColumnModel().getColumn(3).setResizable(false);
    
    tabelaVendaRealizada.getColumnModel().getColumn(4).setPreferredWidth(150);//largura
    tabelaVendaRealizada.getColumnModel().getColumn(4).setResizable(false);
    
    tabelaVendaRealizada.getTableHeader().setResizingAllowed(false);
    tabelaVendaRealizada.setAutoResizeMode(tabelaVendaRealizada.AUTO_RESIZE_OFF);
    tabelaVendaRealizada.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     
     conex.desconecta();
    
    }
    
    public void preencherTabelaDetalhes(String Sql){
    ArrayList dados = new ArrayList();
    String[] colunas = new String[]{"Produtos","Quantidade","Valor Item"};
    conex.conexão();
    conex.execultaSql(Sql);
    try{
        conex.rs.first();
        do{
           dados.add(new Object[]{conex.rs.getString("nome_produto"), conex.rs.getString("quantidade_produto"), conex.rs.getString("preco_venda")});
            
        }while(conex.rs.next());
    }catch(SQLException ex){
        JOptionPane.showMessageDialog(rootPane, "Erro ao preencher um ArrayList!\nErro:"+ex);
    }
    ModeloTabela modelo = new ModeloTabela(dados, colunas);
    
    tabelaDetalhes.setModel(modelo);
    tabelaDetalhes.getColumnModel().getColumn(0).setPreferredWidth(300);//largura
    tabelaDetalhes.getColumnModel().getColumn(0).setResizable(false);

    tabelaDetalhes.getColumnModel().getColumn(1).setPreferredWidth(120);
    tabelaDetalhes.getColumnModel().getColumn(1).setResizable(false);

    tabelaDetalhes.getColumnModel().getColumn(2).setPreferredWidth(120);
    tabelaDetalhes.getColumnModel().getColumn(2).setResizable(false);
    
    tabelaDetalhes.getTableHeader().setResizingAllowed(false);
   tabelaDetalhes.setAutoResizeMode(tabelaDetalhes.AUTO_RESIZE_OFF);
    tabelaDetalhes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     
     
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisaVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPesquisa;
    private javax.swing.JFormattedTextField campoData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaDetalhes;
    private javax.swing.JTable tabelaVendaRealizada;
    // End of variables declaration//GEN-END:variables
}
