/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import ModeloConection.ConexãoSQL;
import ModeloDao.DaoRegistroVendas;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import modeloBeans.BeansRegistroVenda;
import modeloBeans.ModeloTabela;

/**
 *
 * @author iurya
 */
public class RegistroVendas extends javax.swing.JFrame {

    BeansRegistroVenda mod = new BeansRegistroVenda();
    DaoRegistroVendas control = new DaoRegistroVendas();

    ConexãoSQL conex = new ConexãoSQL();
    int flag = 1, codigovenda;
    float precoProduto, total = 0;

    public RegistroVendas() {
        initComponents();
        conex.conexão();

        // try {
        // MaskFormatter form = new MaskFormatter("##/##/####");
        // campoData.setFormatterFactory(new DefaultFormatterFactory(form));
        // } catch (ParseException ex) {
        //    Logger.getLogger(RegistroVendas.class.getName()).log(Level.SEVERE, null, ex);
        //  }
        //formata o campoData
        try {
            MaskFormatter form = new MaskFormatter("##/##/####");//elemento que cria o formato data
            campoData.setFormatterFactory(new DefaultFormatterFactory(form));
        } catch (ParseException ex) {
            Logger.getLogger(RegistroVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
        //formata o campoDesconto
        try {
            MaskFormatter form = new MaskFormatter("##.##");//elemento que cria o formato desconto
            CampoDesconto.setFormatterFactory(new DefaultFormatterFactory(form));
        } catch (ParseException ex) {
            Logger.getLogger(RegistroVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
        //pega data do sistema
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date hoje = new Date();
        campoData.setText(df.format(hoje));
        conex.desconecta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buttonFinalizar = new javax.swing.JButton();
        ButtonCancelar = new javax.swing.JButton();
        CampoNotaFiscal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CampoCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaItens = new javax.swing.JTable();
        ButtonPesquisarCliente = new javax.swing.JButton();
        campoQuantidade = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        campoProduto = new javax.swing.JFormattedTextField();
        butonPesquisarProduto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPesquisa = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        CampoValorItem = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CampoValorTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        campoPagamento = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        buttonAdd = new javax.swing.JButton();
        campoData = new javax.swing.JFormattedTextField();
        CampoDesconto = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario de Vendas");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Venda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 16))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1016, 1000));

        jLabel2.setText("Nota Fiscal:");

        buttonFinalizar.setBackground(new java.awt.Color(0, 255, 51));
        buttonFinalizar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        buttonFinalizar.setText("Finalizar venda");
        buttonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFinalizarActionPerformed(evt);
            }
        });

        ButtonCancelar.setBackground(new java.awt.Color(255, 0, 0));
        ButtonCancelar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ButtonCancelar.setText("Cancelar Venda");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });

        CampoNotaFiscal.setEditable(false);
        CampoNotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNotaFiscalActionPerformed(evt);
            }
        });

        jLabel3.setText("Data  da venda:");

        jLabel4.setText("Cliente:");

        CampoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoClienteActionPerformed(evt);
            }
        });

        tabelaItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaItens);

        ButtonPesquisarCliente.setText("Pesquisar");
        ButtonPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPesquisarClienteActionPerformed(evt);
            }
        });

        campoQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoQuantidadeFocusGained(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 255, 51));
        jButton5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton5.setText("Novo");

        jLabel10.setText("Produto:");

        campoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoProdutoActionPerformed(evt);
            }
        });

        butonPesquisarProduto.setText("Pesquisar");
        butonPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonPesquisarProdutoActionPerformed(evt);
            }
        });

        tabelaPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPesquisaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaPesquisa);

        jLabel11.setText("Quantidade:");

        CampoValorItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoValorItemActionPerformed(evt);
            }
        });

        jLabel12.setText("Valor por item R$: ");

        jLabel6.setText("R$:");

        jLabel5.setText("Valor Desconto:");

        jLabel8.setText("R$:");

        CampoValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoValorTotalActionPerformed(evt);
            }
        });

        jLabel7.setText("Valor Total:");

        jLabel9.setText("Forma de Pagamento:");

        campoPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cartão de Credito", "Cartão de Debito", "Dinheiro", " " }));
        campoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPagamentoActionPerformed(evt);
            }
        });

        jLabel13.setText("Itens da venda:");

        jLabel14.setText("Tabela de pesquisa:");

        buttonAdd.setBackground(new java.awt.Color(0, 255, 0));
        buttonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Finalizar.png"))); // NOI18N
        buttonAdd.setText("Add");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        campoData.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        campoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataActionPerformed(evt);
            }
        });

        CampoDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoDescontoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CampoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonPesquisarCliente)
                                .addGap(37, 37, 37)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(butonPesquisarProduto))
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(173, 173, 173))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(351, 351, 351)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(151, 151, 151)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CampoDesconto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonCancelar)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(CampoValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CampoNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(campoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPesquisarCliente)
                    .addComponent(campoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butonPesquisarProduto))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(CampoValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAdd))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(CampoDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(ButtonCancelar)
                    .addComponent(buttonFinalizar))
                .addGap(135, 135, 135))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(788, 816));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void preencherTabelaCliente(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Código", "Nome"};

        conex.conexão();
        conex.execultaSql(Sql);

        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{conex.rs.getString("id_cliente"), conex.rs.getString("nome")});

            } while (conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher um ArrayList" + ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        tabelaPesquisa.setModel(modelo);
        tabelaPesquisa.getColumnModel().getColumn(0).setPreferredWidth(150);//largura
        tabelaPesquisa.getColumnModel().getColumn(0).setResizable(false);

        tabelaPesquisa.getColumnModel().getColumn(1).setPreferredWidth(558);
        tabelaPesquisa.getColumnModel().getColumn(1).setResizable(false);

        tabelaPesquisa.getTableHeader().setResizingAllowed(false);
        tabelaPesquisa.setAutoResizeMode(tabelaPesquisa.AUTO_RESIZE_OFF);
        tabelaPesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        conex.desconecta();
    }

    public void preencherTabelaProduto(String Sql) {
        ArrayList dados = new ArrayList();
        
        String[] colunas = new String[]{"Código", "Descrição", "Qtd"};
        conex.conexão();
        conex.execultaSql(Sql);

        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{conex.rs.getString("id_produto"), conex.rs.getString("nome_produto"), conex.rs.getString("quantidade")});

            } while (conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher um ArrayList" + ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        tabelaPesquisa.setModel(modelo);
        tabelaPesquisa.getColumnModel().getColumn(0).setPreferredWidth(150);//largura
        tabelaPesquisa.getColumnModel().getColumn(0).setResizable(false);

        tabelaPesquisa.getColumnModel().getColumn(1).setPreferredWidth(408);
        tabelaPesquisa.getColumnModel().getColumn(1).setResizable(false);

        tabelaPesquisa.getColumnModel().getColumn(2).setPreferredWidth(150);//largura
        tabelaPesquisa.getColumnModel().getColumn(2).setResizable(false);

        tabelaPesquisa.getTableHeader().setResizingAllowed(false);
        tabelaPesquisa.setAutoResizeMode(tabelaPesquisa.AUTO_RESIZE_OFF);
        tabelaPesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    public void preencherItensVenda(String Sql) {//erro
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Descrição", "Quantidade", "Valor Total"};
        int qtdVendida;
        float valorProduto;
        conex.conexão();
        conex.execultaSql(Sql);

        try {
            conex.rs.first();
            do {
                valorProduto = conex.rs.getFloat("preco_venda");
                qtdVendida = conex.rs.getInt("quantidade_produto");
                dados.add(new Object[]{conex.rs.getString("nome_produto"), conex.rs.getString("quantidade_produto"), qtdVendida * valorProduto});

            } while (conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher um ArrayList" + ex);
        }

        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        tabelaItens.setModel(modelo);
        tabelaItens.getColumnModel().getColumn(0).setPreferredWidth(350);//largura
        tabelaItens.getColumnModel().getColumn(0).setResizable(false);

        tabelaItens.getColumnModel().getColumn(1).setPreferredWidth(108);
        tabelaItens.getColumnModel().getColumn(1).setResizable(false);

        tabelaItens.getColumnModel().getColumn(2).setPreferredWidth(250);//largura
        tabelaItens.getColumnModel().getColumn(2).setResizable(false);

        tabelaItens.getTableHeader().setResizingAllowed(false);
        tabelaItens.setAutoResizeMode(tabelaItens.AUTO_RESIZE_OFF);
        tabelaItens.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        SomaProduto();
        conex.desconecta();
    }

    public void SomaProduto() {
        total = 0;
        int qtd = 0;
        float valor = 0;
        conex.execultaSql("select * from itens_venda_produto inner join tbprodutos on"
                + " itens_venda_produto.id_produto = tbprodutos.id_produto"
                + " where id_venda =" + codigovenda);

        try {
            // conex.rs.first();
            while (conex.rs.next()) {
                qtd = conex.rs.getInt("quantidade");
                valor = conex.rs.getFloat("preco_venda");
                total = total + conex.rs.getFloat("preco_venda") * conex.rs.getInt("quantidade_produto");
                //JOptionPane.showMessageDialog(null, "qtd "+qtd+" preço venda ="+valor);
            }
            CampoValorTotal.setText(String.valueOf(total - (Float.parseFloat(CampoDesconto.getText()))));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro na soma do total!\nErro:" + ex);
        }

        conex.desconecta();
    }

    private void CampoValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoValorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoValorTotalActionPerformed

    private void ButtonPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPesquisarClienteActionPerformed
        flag = 1;
        preencherTabelaCliente("select * from tbcliente where nome like '%" + CampoCliente.getText() + "%'");
        //CampoCliente.setText("");

    }//GEN-LAST:event_ButtonPesquisarClienteActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        control.CancelaVenda();
        dispose();// fecha a tela
    }//GEN-LAST:event_ButtonCancelarActionPerformed

    private void campoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoProdutoActionPerformed


    }//GEN-LAST:event_campoProdutoActionPerformed

    private void butonPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonPesquisarProdutoActionPerformed
    
        conex.conexão();//faz conexão

        try {
            PreparedStatement pst = conex.con.prepareStatement("insert into tbvenda(valor_venda)values(?)");

            pst.setFloat(1, 0);
            pst.execute();
            conex.execultaSql("select * from tbvenda");
            conex.rs.last();
            codigovenda = conex.rs.getInt("id_venda");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro: " + ex);
        }

        CampoCliente.setEnabled(false);
        ButtonPesquisarCliente.setEnabled(false);
            flag = 2;
        preencherTabelaProduto("select * from tbprodutos Where nome_produto like'%" + campoProduto.getText() + "%'");
        campoProduto.setText("");
        conex.desconecta();
    }//GEN-LAST:event_butonPesquisarProdutoActionPerformed

    private void tabelaPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPesquisaMouseClicked
        if (flag == 1) {
            String nome_cliente = "" + tabelaPesquisa.getValueAt(tabelaPesquisa.getSelectedRow(), 1);
            CampoCliente.setText(nome_cliente);
        } else {
            conex.conexão();
            try {
                String nome_produto = "" + tabelaPesquisa.getValueAt(tabelaPesquisa.getSelectedRow(), 1);
                conex.execultaSql("select * from tbprodutos where nome_produto='" +nome_produto+ "'");
                conex.rs.first();

                precoProduto = conex.rs.getFloat("preco_venda");//conect com BD
                campoProduto.setText(nome_produto);
                CampoValorItem.setText(String.valueOf(precoProduto));
                campoQuantidade.setText("1");//set como padrão a quantidade produto
                CampoDesconto.setText("00.00");//set como padrão desconto = 0

                conex.desconecta();
            } catch (SQLException ex) {
                JOptionPane.showInternalMessageDialog(rootPane, "Erro ao pesquisar preço!");
            }

        }
    }//GEN-LAST:event_tabelaPesquisaMouseClicked

    private void campoQuantidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoQuantidadeFocusGained
        float valorTotal;
        valorTotal = Float.parseFloat(CampoValorItem.getText()) * Integer.parseInt(campoQuantidade.getText());//qtd * valor item
        CampoValorTotal.setText(String.valueOf(valorTotal));
    }//GEN-LAST:event_campoQuantidadeFocusGained

    private void CampoValorItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoValorItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoValorItemActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed

        try {
            int idVenda, quantidade = 0;

            conex.conexão();
            conex.execultaSql("select * from tbprodutos where nome_produto='"+campoProduto.getText()+"'");
            conex.rs.first();
            quantidade = conex.rs.getInt("quantidade");
            
            if (quantidade >= Integer.parseInt(campoQuantidade.getText())) {
                mod.setNomeProduto(campoProduto.getText());
                mod.setQtdItem(Integer.parseInt(campoQuantidade.getText()));
                mod.setIdvenda(codigovenda);
                control.adicionarItem(mod);
                //mod.setNumeroNota(Integer.parseInt(CampoNotaFiscal.getText()));
                //mod.setData(campoData.getDateFormatString());
 
                preencherItensVenda("select * from tbprodutos inner join itens_venda_produto "
                        + "on tbprodutos.id_produto = itens_venda_produto.id_produto inner join tbvenda "
                        + "on tbvenda.id_venda = itens_venda_produto.id_venda where tbvenda.id_venda=" +codigovenda);
            } else {
                JOptionPane.showMessageDialog(rootPane, "A quantidade desejada não está dispoinivel no estoque!");
            }
            //total = total + Float.parseFloat(CampoValorItem.getText()) * Integer.parseInt(campoQuantidade.getText());
            //CampoValorTotal.setText(String.valueOf(total));

        } catch (SQLException ex) {
            JOptionPane.showInternalMessageDialog(rootPane, "Erro ao pesquisar a quantidade!\nErro:" + ex);
         conex.desconecta();
        }
        
    }//GEN-LAST:event_buttonAddActionPerformed

    private void CampoNotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNotaFiscalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNotaFiscalActionPerformed

    private void campoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPagamentoActionPerformed

    private void CampoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoClienteActionPerformed

    private void campoDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataActionPerformed

    private void buttonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFinalizarActionPerformed

        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");

        try {
            Date date = formatter.parse(campoData.getText());
            mod.setData(date);
        } catch (ParseException e) {
            mod.setData(new Date());
        }

        mod.setIdvenda(codigovenda);
        mod.setNomeCliente(CampoCliente.getText());
        mod.setValorDesconto(Float.parseFloat(CampoDesconto.getText()));
        mod.setValorVenda(Float.parseFloat(CampoValorTotal.getText()));
        mod.setFormaPagamento((String) campoPagamento.getSelectedItem());
        control.FecharVenda(mod);
        dispose();


    }//GEN-LAST:event_buttonFinalizarActionPerformed

    private void CampoDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoDescontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoDescontoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonPesquisarCliente;
    private javax.swing.JTextField CampoCliente;
    private javax.swing.JFormattedTextField CampoDesconto;
    private javax.swing.JTextField CampoNotaFiscal;
    private javax.swing.JTextField CampoValorItem;
    private javax.swing.JTextField CampoValorTotal;
    private javax.swing.JButton butonPesquisarProduto;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonFinalizar;
    private javax.swing.JFormattedTextField campoData;
    private javax.swing.JComboBox<String> campoPagamento;
    private javax.swing.JFormattedTextField campoProduto;
    private javax.swing.JTextField campoQuantidade;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaItens;
    private javax.swing.JTable tabelaPesquisa;
    // End of variables declaration//GEN-END:variables
}
