/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import ModeloConection.ConexãoSQL;

/**
 *
 * @author iurya
 */
public class TelaPrincipal extends javax.swing.JFrame {
// canectando com banco de dados
    ConexãoSQL conecta = new ConexãoSQL(); 
            
    public TelaPrincipal() {
        
        initComponents();
        conecta.conexão();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgvendas = new javax.swing.JLabel();
        ButonVendas = new javax.swing.JButton();
        imgClientes = new javax.swing.JLabel();
        butonCliente = new javax.swing.JButton();
        ImgProduto = new javax.swing.JLabel();
        ButtonProdutos = new javax.swing.JButton();
        imgRelatorios = new javax.swing.JLabel();
        ButonRelatorios = new javax.swing.JButton();
        imgFornecedor = new javax.swing.JLabel();
        ButonFornecedor = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        OpçãoCadastroCliente = new javax.swing.JMenuItem();
        OpçãocadastroCliente = new javax.swing.JMenuItem();
        OpçãoCadastroUsuario = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        MenuFerramentas = new javax.swing.JMenu();
        MenuSair = new javax.swing.JMenu();
        jMenuItem4Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Vendas\n");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        imgvendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/business_salesreport_salesreport_negocio_2353.png"))); // NOI18N

        ButonVendas.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        ButonVendas.setText("Vendas");
        ButonVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButonVendasActionPerformed(evt);
            }
        });

        imgClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/businessapplication_edit_male_user_thepencil_theclient_negocio_2321.png"))); // NOI18N
        imgClientes.setText("jLabel2");

        butonCliente.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        butonCliente.setText("Clientes");
        butonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonClienteActionPerformed(evt);
            }
        });

        ImgProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stuffitboxproduct_stuffit_caj_2624.png"))); // NOI18N
        ImgProduto.setText("jLabel3");

        ButtonProdutos.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        ButtonProdutos.setText("Produtos");
        ButtonProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProdutosActionPerformed(evt);
            }
        });

        imgRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/up_high_sales_business_finance_icon-icons.com_76287.png"))); // NOI18N
        imgRelatorios.setText("jLabel4");

        ButonRelatorios.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        ButonRelatorios.setText("Relatorios");
        ButonRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButonRelatoriosActionPerformed(evt);
            }
        });

        imgFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/customer_person_people_man_you_1626.png"))); // NOI18N
        imgFornecedor.setText("jLabel5");

        ButonFornecedor.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        ButonFornecedor.setText("Fornecedor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(imgRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(imgFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(ImgProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(imgvendas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ButonRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButonFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butonCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ButonVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(935, 935, 935))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(imgvendas)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ButonVendas)
                        .addGap(34, 34, 34)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butonCliente)
                    .addComponent(imgClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ImgProduto)
                    .addComponent(ButtonProdutos))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imgRelatorios)
                    .addComponent(ButonRelatorios))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButonFornecedor)
                    .addComponent(imgFornecedor))
                .addGap(169, 169, 169))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(12, 36, 1169, 670);

        menuCadastros.setText("Cadastros");

        OpçãoCadastroCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        OpçãoCadastroCliente.setText("Cliente");
        OpçãoCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpçãoCadastroClienteActionPerformed(evt);
            }
        });
        menuCadastros.add(OpçãoCadastroCliente);

        OpçãocadastroCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        OpçãocadastroCliente.setText("Produtos");
        OpçãocadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpçãocadastroClienteActionPerformed(evt);
            }
        });
        menuCadastros.add(OpçãocadastroCliente);

        OpçãoCadastroUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        OpçãoCadastroUsuario.setText("Usuarios");
        menuCadastros.add(OpçãoCadastroUsuario);

        jMenuBar1.add(menuCadastros);

        menuRelatorios.setText("Pesquisas");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Vendas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuRelatorios.add(jMenuItem5);

        jMenuBar1.add(menuRelatorios);

        MenuFerramentas.setText("Ferramentas");
        jMenuBar1.add(MenuFerramentas);

        MenuSair.setText("Sair");

        jMenuItem4Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4Sair.setText("Sair");
        jMenuItem4Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4SairActionPerformed(evt);
            }
        });
        MenuSair.add(jMenuItem4Sair);

        jMenuBar1.add(MenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1211, 809));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OpçãoCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpçãoCadastroClienteActionPerformed
         FormularioClientes tela = new FormularioClientes();
        tela.setVisible(true);
    }//GEN-LAST:event_OpçãoCadastroClienteActionPerformed

    private void OpçãocadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpçãocadastroClienteActionPerformed
        CadastroProdutos tela = new CadastroProdutos();
        tela.setVisible(true);
    }//GEN-LAST:event_OpçãocadastroClienteActionPerformed

    private void butonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonClienteActionPerformed
        FormularioClientes tela = new FormularioClientes();
        tela.setVisible(true);
    }//GEN-LAST:event_butonClienteActionPerformed

    private void ButonVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonVendasActionPerformed
        RegistroVendas tela = new RegistroVendas();
        tela.setVisible(true);        
    }//GEN-LAST:event_ButonVendasActionPerformed

    private void jMenuItem4SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4SairActionPerformed
       conecta.desconecta();//encerra conecxão Banco de Dados
        System.exit(0);
        
    }//GEN-LAST:event_jMenuItem4SairActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        PesquisaVendas tela = new PesquisaVendas();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void ButtonProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProdutosActionPerformed
        CadastroProdutos tela = new CadastroProdutos();
        tela.setVisible(true);
    }//GEN-LAST:event_ButtonProdutosActionPerformed

    private void ButonRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonRelatoriosActionPerformed
        TelaRelatorio tela = new TelaRelatorio();
        tela.setVisible(true);
    }//GEN-LAST:event_ButonRelatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButonFornecedor;
    private javax.swing.JButton ButonRelatorios;
    private javax.swing.JButton ButonVendas;
    private javax.swing.JButton ButtonProdutos;
    private javax.swing.JLabel ImgProduto;
    private javax.swing.JMenu MenuFerramentas;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenuItem OpçãoCadastroCliente;
    private javax.swing.JMenuItem OpçãoCadastroUsuario;
    private javax.swing.JMenuItem OpçãocadastroCliente;
    private javax.swing.JButton butonCliente;
    private javax.swing.JLabel imgClientes;
    private javax.swing.JLabel imgFornecedor;
    private javax.swing.JLabel imgRelatorios;
    private javax.swing.JLabel imgvendas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4Sair;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuRelatorios;
    // End of variables declaration//GEN-END:variables
}
